---
abstract: 'OO test script golf sugar'
author:
  - 'Daniel Perrett <perrettdl@googlemail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Proto
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  Moo: 0
  Object::ID: v0.0.5
  Scalar::Util: 1.14
  Test::Deep::NoTest: 0
  Test::More: 0
resources:
  bugtracker: http://github.com/pdl/Test-Proto/issues
  homepage: http://github.com/pdl/Test-Proto
  repository: http://github.com/pdl/Test-Proto
version: 0.022
