--- #YAML:1.0
name:               Test-Proto
version:            0.011
abstract:           OO test script golf sugar
author:
    - Daniel Perrett <perrettdl@googlemail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:        0
    Test::Deep::NoTest:  0
    Test::More:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
